version: "3"
networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: ${IP_SUBNET}
services:
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ../code/animeheaven.sql:/docker-entrypoint-initdb.d/animeheaven.sql
    networks:
      my_network:
        ipv4_address: ${IP_MYSQL}
    ports:
      - "3306:3306"

  web:
    image: php:7.2.2-apache
    container_name: php_web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ../code/:/var/www/html/
    env_file:
      - ../code/.env
    ports:
      - ${PORT_WEB}:80
    tty: true
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - ${PORT_PMA}:80
    networks:
      - my_network