version: "3"
networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.96.0/24
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: animeheaven
      MYSQL_USER: tonyo
      MYSQL_PASSWORD: password
    volumes:
      - ../Project_Devops_code/animeheaven.sql:/docker-entrypoint-initdb.d/animeheaven.sql
    networks:
      my_network:
        ipv4_address: 192.168.96.2
    ports:
      - "3306:3306"

  web:
    image: php:7.2.2-apache
    container_name: php_web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ../Project_Devops_code/:/var/www/html/
    ports:
      - "8080:80"
    tty: true
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    networks:
      - my_network