---
# Get project from github
- name: Get Projet from Github
  git:
    repo: https://github.com/TonyoCallimoutou/Project_Devops_code
    dest: /home/vagrant/projet/code

# Copy file
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/vagrant/projet/docker
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml
  copy:
    src: ../../../docker-compose.yml
    dest: /home/vagrant/projet/docker/docker-compose.yml

- name: Copy Dockerfile
  copy:
    src: ../../../Dockerfile
    dest: /home/vagrant/projet/docker/Dockerfile

- name: Copy .env for Docker compose
  copy:
    src: ../../../.env
    dest: /home/vagrant/projet/docker/.env

- name: Copy .env for Code
  copy:
    src: ../../../.env
    dest: /home/vagrant/projet/code/.env

# RUN Docker
- name: Run docker-compose
  shell: 
    cmd: "sudo docker-compose up -d"
    chdir: /home/vagrant/projet/docker